# Generated by Django 4.2.7 on 2024-05-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_carausel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carausel',
        ),
    ]
